pihps_pipeline:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT', 'radar-pangan-hackathon') }}"
      dataset: raw
      location: "{{ env_var('BQ_LOCATION', 'asia-southeast2') }}"
      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1
